global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/templates.tmpl'

route:
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'default'

  routes:
    - match:
        severity: critical
      receiver: 'critical-team'

    - match:
        severity: warning
      receiver: 'ops-team'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'https://webhook.site'

  - name: 'critical-team'
    webhook_configs:
      - url: 'https://webhook.site'

  - name: 'ops-team'
    webhook_configs:
      - url: 'https://webhook.site'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
